export const API = process.env.REACT_APP_API_URL

export const EMAIL_CONFIG = {
  REACT_APP_EMAILJS_RECEIVER: process.env.REACT_APP_EMAILJS_RECEIVER,
  REACT_APP_EMAILJS_TEMPLATEID: process.env.REACT_APP_EMAILJS_TEMPLATEID,
  REACT_APP_EMAILJS_USERID: process.env.REACT_APP_EMAILJS_USERID
};